version: 1.2
workflows:
  - subclass: WDL 
    primaryDescriptorPath: /workflows/susieR.wdl
    name: "SusieR"
  - subclass: WDL 
    primaryDescriptorPath: /workflows/prepInputsSusieR.wdl
    name: "PrepSusieR"
  - subclass: WDL 
    primaryDescriptorPath: /workflows/susieRonly.wdl
    name: "SusieRonly"
  - subclass: WDL 
    primaryDescriptorPath: /workflows/ComputeR2Susie.wdl
    name: "ComputeR2Susie"
  - subclass: WDL 
    primaryDescriptorPath: /workflows/AggregateSusie.wdl
    name: "AggregateSusie"
  - subclass: WDL
    primaryDescriptorPath: /workflows/AggregateSusieTask.wdl
    name: "AggregateSusieTask"
  - subclass: WDL
    primaryDescriptorPath: /workflows/AnnotateSusie.wdl
    name: "AnnotateSusie"
