version: 1.2
workflows:
  - subclass: WDL 
    primaryDescriptorPath: /susieR/susieR.wdl
    name: "SusieR"
  - subclass: WDL 
    primaryDescriptorPath: /susieR/prepInputsSusieR.wdl
    name: "PrepSusieR"
  - subclass: WDL 
    primaryDescriptorPath: /susieR/susieRonly.wdl
    name: "SusieRonly"
  - subclass: WDL 
    primaryDescriptorPath: /susieR/ComputeR2Susie.wdl
    name: "ComputeR2Susie"

