# Shared import and input-normalization helpers used by the fine-mapping and
# cross-validation entrypoint scripts. These functions convert Terra/WDL input
# files into matrices, metadata tables, and lists expected by the SuSiE code.

# Read an optional single-column variant allowlist and return variant IDs.
ImportVariantList <- function(VariantListPath) {
    VariantList <- readr::read_tsv(VariantListPath) %>% 
                        dplyr::rename('variants'  = 1) %>% 
                        pull(variants)
    VariantList
}

# Load QTL covariates and orient them as a sample x covariate numeric matrix.
importQtlmapCovariates <- function(covariates_path,load_colnames = FALSE){
  pc_matrix = read.table(covariates_path, check.names = FALSE, header = TRUE, stringsAsFactors = FALSE)
  col_names <-  pc_matrix %>% pull(ID)
  pc_transpose = t(pc_matrix[,-1])
  colnames(pc_transpose) = pc_matrix$SampleID
  pc_df = dplyr::mutate(as.data.frame(pc_transpose), genotype_id = rownames(pc_transpose)) %>%
    dplyr::as_tibble() %>% 
    dplyr::select(genotype_id, dplyr::everything())
  
  # Drop the sample ID column and preserve sample IDs as row names for later
  # alignment with expression and genotype matrices.
  pc_matrix = as.matrix(dplyr::select(pc_df,-genotype_id))
  rownames(pc_matrix) = pc_df$genotype_id
  if (load_colnames == TRUE) {
      colnames(pc_matrix) <- col_names
  }
  return(pc_matrix)
}

# Load tensorQTL permutation output and add the fields expected downstream.
importQtlmapPermutedPvalues <- function(perm_path){
  tbl = read.table(perm_path, check.names = FALSE, header = TRUE, stringsAsFactors = FALSE) %>%
    dplyr::as_tibble() %>%
    dplyr::mutate(p_fdr = qval) %>% 
    #dplyr::mutate(p_fdr = p.adjust(pval_beta, method = "fdr")) %>%
    dplyr::mutate(group_id = phenotype_id)
  return(tbl)
}


# Group samples by ancestry and create balanced cross-validation fold IDs.
CreateCVFoldsMetadata <- function(SampleMetadataPath,AncestryDf,nFolds = 5) {
require(caret)
SampleMetadata <- readr::read_tsv(SampleMetadataPath) %>% 
        dplyr::rename('sample_id' =1 ) %>% 
        mutate(genotype_id = sample_id,qtl_group = 'ALL') %>% 
        mutate(sample_id = as.numeric(sample_id),genotype_id = as.character(genotype_id))  %>%
        left_join(AncestryDf,by = c('sample_id' = 'research_id')) %>% 
        group_by(ancestry_pred_other) %>%
        group_modify(~ {
            .x$fold <- createFolds(seq_len(nrow(.x)), k = nFolds, list = FALSE)
            .x
        }) %>%
        ungroup()
SampleMetadata
}

# Load sample ancestry labels used for per-ancestry MAF filtering and CV folds.
LoadAncestryData <- function(AncestryPath) {
message('Loading ancestry data')
AncestryDat <- readr::read_tsv(AncestryPath) %>% 
    select(research_id,ancestry_pred_other) %>%
    mutate(research_id = as.numeric(research_id))
AncestryDat
}

# Load the serialized CV metadata/PC object generated by PrepSusieCVPCs.R.
LoadCVData <- function(CVobj) {
#require(qs2)
message('Loading CV PCs and metadata ')
CVDat <- readRDS(CVobj)
}

# Load extra genotype features, such as structural variants, for optional
# inclusion in fine-mapping.
ImportAdditionalGenotypes <- function(AdditionalGenotypesBed) {
AdditionalGenotypes <- fread(AdditionalGenotypesBed,header = TRUE) %>% 
    dplyr::rename('variant_id' = 1,'phenotype_id' = 2,'feature_type' = 3)
AdditionalGenotypes
}

# Main data loader used by susie.R and ComputeR2Susie.R. It validates required
# inputs, loads molecular/covariate/QTL data, and returns a named list that is
# injected into the caller environment.
LoadData <- function(opt_list) {
    require(data.table)
    message('Loading molecular data')
    
    if (is.null(opt_list$expression_matrix)) {
        stop('molecular data file is missing')
    }
    if (is.null(opt_list$phenotype_list)) {
        stop('tensorQTL file is missing')
    }
    if (is.null(opt_list$covariates)) {
        stop('Covariates file is missing')
    }
    if (is.null(opt_list$genotype_matrix)) {
        stop('Genotype file is missing')
    }
     
    expression_matrix = fread(opt_list$expression_matrix,header = TRUE) %>% dplyr::rename('phenotype_id' = 4)
    subset_matrix <- expression_matrix %>% select(1,2,3,4)
    print(colnames(subset_matrix))
    message('Loading covariates')
    
    if(!is.null(opt_list$cv_meta)) {
        covariates_matrix = importQtlmapCovariates(opt_list$covariates,load_colnames = TRUE)
    } else {
        covariates_matrix = importQtlmapCovariates(opt_list$covariates,load_colnames = FALSE)
    }
    exclude_cov = apply(covariates_matrix, 2, sd) != 0
    covariates_matrix = covariates_matrix[,exclude_cov]

    # Convert BED columns into phenotype metadata required by eQTLUtils.
    phenotype_meta<- expression_matrix %>% 
        select(1,2,3,4) %>% 
        dplyr::rename('chromosome' = 1,'phenotype_pos' = 2) %>% 
        mutate(strand  = 1) %>% 
        mutate(gene_id = phenotype_id,group_id = phenotype_id) %>%
        select(phenotype_id,group_id,gene_id,chromosome,phenotype_pos,strand)
    # Convert the sample list into the sample metadata shape required by
    # eQTLUtils; CV workflows can omit this because metadata is stored in CV RDS.
    message('Loading sample metadata')
    if(is.null(opt_list$cv_meta) && is.null(opt_list$sample_meta)) {
          stop('Sample metadata missing')
        }  
    if (!is.null(opt_list$sample_meta)) {
            sample_metadata <-  readr::read_tsv(opt_list$sample_meta) %>% 
                dplyr::rename('sample_id' =1 ) %>% 
                mutate(genotype_id = sample_id,qtl_group = 'ALL') %>% 
                mutate(sample_id = as.character(sample_id),genotype_id = as.character(genotype_id))
            }else {
            sample_metadata <- NULL
        }
    if (!is.null(opt_list$cv_meta)) {
            cv_meta <- LoadCVData(opt_list$cv_meta)  
                        
            }else {
            cv_meta <- NULL
        }
    # Import permutation p-values from tensorQTL and keep only phenotypes that
    # pass the current FDR threshold.
    message('Loading QTL stats')
    
    
    phenotype_table = importQtlmapPermutedPvalues(opt_list$phenotype_list)

    filtered_list = dplyr::filter(phenotype_table, p_fdr < 0.05) 
    phenotype_list = dplyr::semi_join(
        phenotype_table %>% dplyr::select(group_id, phenotype_id) %>% dplyr::distinct(),
        filtered_list %>% dplyr::select(group_id) %>% dplyr::distinct(),
        by = "group_id"
    )
    # Keep only phenotypes that are present in the expression matrix.
    phenotype_list = dplyr::filter(phenotype_list, phenotype_id %in% expression_matrix$phenotype_id)
    message("Number of phenotypes included for analysis: ", nrow(phenotype_list))
    if (nrow(phenotype_list) == 0) {
        stop('No phenotypes found matching between phenotype table and expression matrix')
    }

    if (!is.null(opt_list$AncestryMetadata)) {
        AncestryDf <- LoadAncestryData(opt_list$AncestryMetadata)
    }else {
        AncestryDf <- NULL
    }
    #if (!is.null(opt_list$n_folds)) {
        #n_folds <- as.numeric(opt_list$n_folds) 
        #}else {
        #n_folds <- NULL
    #}
   
    # Collect scalar inputs and optional filters in a single output list for the
    # entrypoint scripts.
    genotype_file <- opt_list$genotype_matrix
    cis_distance <- as.numeric(opt_list$cisdistance)
    output_prefix <- opt_list$out_prefix
    n_folds <- opt_list$n_folds
    variant_list <- opt_list$VariantList
    MAF_threshold <- opt_list$MAF
    region_df <- phenotype_meta %>% 
                    filter(phenotype_id %in% phenotype_list$phenotype_id) %>% 
                    transmute(phenotype_id,region = paste0(chromosome,':',
                                                           phenotype_pos - cis_distance,'-',
                                                           phenotype_pos + cis_distance))
    if (!is.null(opt_list$AdditionalGenotypesBed)) {
        # Additional genotypes are subset to phenotypes being fine-mapped and
        # stored as a variant x sample matrix before merging into dosage data.
        message('Loading additional genotypes')
        additional_genotypes <- ImportAdditionalGenotypes(opt_list$AdditionalGenotypesBed)  %>% 
            filter(phenotype_id %in% phenotype_list$phenotype_id) %>% 
            dplyr::select(-2,-3) %>% 
            tibble::column_to_rownames('variant_id') %>% 
            data.matrix()
    } else {
        additional_genotypes <- NULL
    } 

    OutList <- list(
        covariates_matrix = covariates_matrix,
        phenotype_table = phenotype_table,
        phenotype_meta = phenotype_meta,
        filtered_list = filtered_list,
        phenotype_list = phenotype_list,
        expression_matrix = expression_matrix,
        variant_list = variant_list,
        MAF_threshold = MAF_threshold,
        AncestryDf = AncestryDf,
        output_prefix = output_prefix,
        cis_distance = cis_distance,
        genotype_file = genotype_file,
        sample_metadata = sample_metadata,
        region_df = region_df,
        cv_meta = cv_meta,
        additional_genotypes = additional_genotypes
        )
    OutList
}
